
backend:
  name: git-gateway
local_backend: true
media_folder: src/content/images
public_folder: ./images


collections:
  - name: blog
    editor: { preview: false }
    label: Blog
    folder: src/content/blog
    slug: '{{slug}}'
    media_folder: 'images/{{slug}}'
    public_folder: './images/{{slug}}'
    create: true
    fields:
      - {
        label: Title, 
        name: title, 
        widget: string,
        required: true
      }
      - {
        label: Description, 
        name: description, 
        widget: text,
        required: true
      }
      - {
        label: Publish Date, 
        name: pubDate, 
        widget: datetime,
        format: "MMM DD YYYY",
        required: true
      }
      - {
        label: Featured Image, 
        name: heroImage, 
        widget: image,
        required: true
      }
      - {
        label: Body, 
        name: body, 
        widget: markdown,
        required: true
      }


  - label: "Pages"
    name: "pages"
    files:
      - label: "Hero"
        name: "hero"
        editor: { preview: false }
        file: "src/content/hero/index.md"
        media_folder: 'images'
        public_folder: './images'
        fields:
          - {
            label: Body,
            name: body,
            widget: markdown,
            editor_components: [],
            required: true
          }
          - {
            label: Image,
            name: image,
            widget: image,
            required: true
          }
      - label: "About"
        name: "about"
        editor: { preview: false }
        file: "src/content/about/index.md"
        media_folder: 'images'
        public_folder: './images'
        fields:
          - {
            label: Body,
            name: body,
            widget: markdown,
            required: true
          }

      - label: "Social"
        name: "social"
        editor: { preview: false }
        file: "src/content/social/index.md"
        media_folder: 'images'
        public_folder: './images'
        fields:
          - label: Socials
            name: socials
            widget: list
            required: true
            summary: '{{fields.url}}'
            fields:
              - label: url
                name: url
                widget: text
              - label: icon
                name: icon
                widget: image
                required: true
                